# -*- coding: utf-8 -*-
"""Copy of simple_langchain_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11G9l-Il6X1C7z1VgHTgrT-jHcIuDYmPM

# **Simple Agent using Langchain**
# **LLM Agents** with LangChain
"""

!pip install -qU "langchain==0.3.*" "langchain-core>=0.3.78,<0.4" "langchain-community==0.3.*" "langchain-openai==0.3.*"
!pip install -qU pyowm

import os

"""### Initialize OpenAI LLM"""

from langchain_openai import ChatOpenAI

# Set OpenAI API key
os.environ['OPENAI_API_KEY'] = "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"

# Initialize the ChatOpenAI model
llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

query = "Current temperature in Colombo?"
result = llm.invoke(query)
print(result.content)

query = "President in sri lanka?"
result = llm.invoke(query)
print(result.content)

"""### Initialize Google Search Tool

Link: https://app.tavily.com/home
here if we want we can crate this account for free
"""

from langchain_community.tools.tavily_search import TavilySearchResults

os.environ['TAVILY_API_KEY'] = "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"

search_tool = TavilySearchResults(max_results=2, search_depth='advanced',max_tokens=5000)

"""### Initialize OpenWeatherMap Tool

Link: https://openweathermap.org/api
"""

from langchain_community.utilities import OpenWeatherMapAPIWrapper
from langchain.agents import load_tools

os.environ["OPENWEATHERMAP_API_KEY"] = "4c0113d32192a14b56b2cbe7e2c88ea1"

# Initialize OpenWeatherMap tool
weather = OpenWeatherMapAPIWrapper()

weather_tool = load_tools(["openweathermap-api"], llm)[0]

weather_tool

tools = [search_tool, weather_tool]

print(tools)

"""### Load Prompt Template from LangChainHub"""

from langchain import hub

# Pull the prompt template from LangChainHub
prompt = hub.pull("hwchase17/react")

print(prompt)

from langchain.agents import create_react_agent
from langchain.agents import AgentExecutor

# Create a new agent with the DuckDuckGo search tool, OpenWeatherMap tool  and custom word count tool
agent = create_react_agent(tools = tools, llm = llm, prompt=prompt)

# Initialize the agent executor with the new agent and tools
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, handle_parsing_errors=True)

"""### Invoke the custom agent executor with example questions"""

response = agent_executor.invoke({"input": "what is machine learning?"})

print(response['output'])

response = agent_executor.invoke({"input": "current president in srilanka"})

print(response['output'])

response = agent_executor.invoke({"input": "Current temperature in Galle?"})

print(response['output'])

response = agent_executor.invoke({"input": "what is the temperature of the city where 'lotus tower' is located?"})

print(response['output'])

response = agent_executor.invoke({"input": "where hapugale situated"})

print(response['output'])